console.log('Initializing database...');
require('./Task');
require('./Link');
require('./Question');
require('./Option');
require('./Institution');
require('./Teacher');
require('./Course');
require('./Team');
require('./Student');
require('./StudentTeam');
require('./Admin');
require('./TaskAttempt');
require('./Answer');
require('./AnswerAudio');
